<a href="https://colab.research.google.com/github/yeoauqt/229352/blob/main/Lab08_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [1]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [11]:
a = torch.tensor(2)
a

tensor(2)

In [12]:
b = torch.tensor(3)
b

tensor(3)

### Convert a tensor to scalar

In [14]:
c = b.item()
c

3

### Creating 2D tensor

In [15]:
A = torch.tensor([[1, 2], [5, 6]])
A

tensor([[1, 2],
        [5, 6]])

## Tensor and Numpy

### Convert from tensor to numpy array

In [16]:
B = A.numpy()
B

array([[1, 2],
       [5, 6]])

### Convert from numpy array to tensor

In [7]:
C = torch.from_numpy(B)
C

tensor([[1, 2],
        [5, 6]])

## PyTorch and GPU

check if GPU is available

In [17]:
torch.cuda.is_available()

True

In [18]:
C.device

device(type='cpu')

In [19]:
D = C.cuda()
D

tensor([[1, 2],
        [5, 6]], device='cuda:0')

In [20]:
D.device

device(type='cuda', index=0)

In [21]:
C + D # บวกกันไม่ได้

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [22]:
D.numpy() # ไม่สามารถแปลงเป็น numpy ได้

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [23]:
E = D.cpu().numpy()
E

array([[1, 2],
       [5, 6]])

## Basic operations

In [24]:
E * 2

array([[ 2,  4],
       [10, 12]])

In [25]:
E - 2

array([[-1,  0],
       [ 3,  4]])

In [26]:
D - 2

tensor([[-1,  0],
        [ 3,  4]], device='cuda:0')

In [27]:
D.cpu() * np.array([1, 2])

/tmp/ipython-input-4124694458.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  D.cpu() * np.array([1, 2])


tensor([[ 1,  4],
        [ 5, 12]])

### Matrix multiplication

In [28]:
A = torch.tensor([[4, 5], [8, 9]])
B = torch.tensor([[1, 4], [7, 8]])

torch.matmul(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [29]:
torch.mm(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [30]:
A @ B

tensor([[ 39,  56],
        [ 71, 104]])

### Matrix transpose

In [31]:
A

tensor([[4, 5],
        [8, 9]])

In [32]:
A.t()

tensor([[4, 8],
        [5, 9]])

## Creating a specific type of tensor

In [33]:
a = torch.zeros(1, 2, 3)
a

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [34]:
b = torch.ones(1, 2, 3)
b

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [35]:
I = torch.eye(3)
I

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [36]:
R1 = torch.rand(2, 3)
R1

tensor([[0.8934, 0.6051, 0.9489],
        [0.0087, 0.2066, 0.1396]])

In [37]:
R2 = torch.randn(2, 3)
R2

tensor([[-1.0075, -0.4843, -0.7383],
        [ 0.4210,  0.1304, -1.8796]])

## Tensor's shape

### Checking the shape of a tensor

In [38]:
A.shape

torch.Size([2, 2])

In [39]:
A.size()

torch.Size([2, 2])

### Changing the shape of a tensor

In [41]:
u = torch.arange(6)
u.shape

torch.Size([6])

In [42]:
v = u.reshape(2, 3)
v.shape

torch.Size([2, 3])

In [43]:
w = u.view(3, 2)
w

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [44]:
a = torch.arange(4)
b = torch.arange(4) + 1

c = torch.stack([a, b], dim=0)
c

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4]])

In [45]:
d = torch.stack([a, b], axis=1)
d

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

In [46]:
a

tensor([0, 1, 2, 3])

In [47]:
b

tensor([1, 2, 3, 4])

In [48]:
# concatenate
e = torch.cat([a, b], dim=0)
e

tensor([0, 1, 2, 3, 1, 2, 3, 4])

In [49]:
f = torch.cat([a, b], axis=1) # error
f

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

### Squeezing a tensor (removing an extra dimension)

In [50]:
A = torch.zeros(1, 2, 3)
B.squeeze()

B

tensor([[1, 4],
        [7, 8]])

In [51]:
B.shape

torch.Size([2, 2])

### Unsqueezing a tensor (adding an extra dimension)

In [52]:
# H.shape = (6, )
C = B.unsqueeze(axis=0)
C.shape

torch.Size([1, 2, 2])

## Indexing

In [53]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


In [54]:
P[[0, 1, 2], [0, 1, 2]]
P[0:3, 0:3]

tensor([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10]])

In [55]:
torch.inverse(torch.tensor([[2.0, 0.0], [0.0, 5.0]]))

tensor([[0.5000, 0.0000],
        [0.0000, 0.2000]])

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [56]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


In [57]:
# Create three random 𝑁(0,1) tensors: X, b and e

X = torch.randn(200, 7) # X.shape = (200, 7)
b = torch.randn(8, 1) # b.shape = (8, 1)
e = torch.randn(200, 1) # e.shape = (200, 1)

In [58]:
# Create a tensor that contains only 1's with shape (200, 1)

ones = torch.ones(200, 1)
ones.shape

torch.Size([200, 1])

In [59]:
# Modify tensor X by adding the tensor in 2. as the first column.

X = torch.cat((ones, X), dim=1)

In [60]:
# Compute y

y = torch.matmul(X, b) + e

In [64]:
# Fit a linear regression to the data X and y

xt_x_inv = torch.inverse(torch.matmul(X.T, X))
xt_y = torch.matmul(X.T, y)


# obtain a tensor of estimated coefficient b_hat

b_hat = torch.matmul(xt_x_inv, xt_y)
b_hat

tensor([[ 0.2387],
        [ 0.0077],
        [-0.6406],
        [ 1.5296],
        [ 0.0464],
        [ 1.5935],
        [-0.0902],
        [ 0.8830]])

In [65]:
# Compute the predictions y_hat

y_hat = torch.matmul(X, b_hat)
y_hat

tensor([[ 1.3168e+00],
        [ 9.0383e-01],
        [ 3.3412e+00],
        [ 1.5076e+00],
        [ 3.7207e+00],
        [ 3.3238e-02],
        [-1.0082e+00],
        [ 1.7521e+00],
        [-1.6556e+00],
        [ 1.6531e-01],
        [-6.3344e-01],
        [ 2.6689e-01],
        [ 8.5572e-01],
        [-3.5003e+00],
        [-3.0851e-01],
        [ 3.1598e-01],
        [-1.4693e+00],
        [-2.4432e+00],
        [ 1.6636e-01],
        [-3.4796e+00],
        [ 2.9671e+00],
        [ 1.4378e+00],
        [ 1.5508e+00],
        [-2.5919e+00],
        [-1.9620e+00],
        [ 4.1802e-01],
        [ 3.5529e+00],
        [-3.4274e-01],
        [ 1.4043e+00],
        [ 5.8063e+00],
        [-2.7990e+00],
        [-8.4209e-01],
        [-4.1573e-01],
        [-1.5019e+00],
        [ 1.8151e+00],
        [-2.7537e+00],
        [-2.5401e+00],
        [ 4.8285e-01],
        [-1.2504e+00],
        [ 3.1814e-01],
        [-2.5920e+00],
        [ 1.0754e-01],
        [ 2.5405e-01],
        [-1

In [67]:
# Convert both y and y_hat from tensor to Numpy array and calculate MSE

y_np = y.numpy()
y_hat_np = y_hat.numpy()

mse = np.mean((y_np - y_hat_np)**2)
print(mse)

0.8722147
